// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzwLpr-NILlAM6bMVK0ep0q5YsvW1HUag',
    appId: '1:111720121979:web:290c44027911fae55984de',
    messagingSenderId: '111720121979',
    projectId: 'disaster-reporting-app-hp-2026',
    authDomain: 'disaster-reporting-app-hp-2026.firebaseapp.com',
    storageBucket: 'disaster-reporting-app-hp-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1QLYFoU0uOdFv5FB6z4z0CsqV_rEJn0',
    appId: '1:111720121979:android:b67c75339de5e9525984de',
    messagingSenderId: '111720121979',
    projectId: 'disaster-reporting-app-hp-2026',
    storageBucket: 'disaster-reporting-app-hp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX1StKKgYeIbZ0TyUa2RYNaIYLc_HtXGA',
    appId: '1:111720121979:ios:2b6bc525cc2686ef5984de',
    messagingSenderId: '111720121979',
    projectId: 'disaster-reporting-app-hp-2026',
    storageBucket: 'disaster-reporting-app-hp-2026.firebasestorage.app',
    iosBundleId: 'com.example.disasterReportingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX1StKKgYeIbZ0TyUa2RYNaIYLc_HtXGA',
    appId: '1:111720121979:ios:2b6bc525cc2686ef5984de',
    messagingSenderId: '111720121979',
    projectId: 'disaster-reporting-app-hp-2026',
    storageBucket: 'disaster-reporting-app-hp-2026.firebasestorage.app',
    iosBundleId: 'com.example.disasterReportingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzwLpr-NILlAM6bMVK0ep0q5YsvW1HUag',
    appId: '1:111720121979:web:23aeb125ec7147d75984de',
    messagingSenderId: '111720121979',
    projectId: 'disaster-reporting-app-hp-2026',
    authDomain: 'disaster-reporting-app-hp-2026.firebaseapp.com',
    storageBucket: 'disaster-reporting-app-hp-2026.firebasestorage.app',
  );
}
